name: AltHelper
version: ${version}
main: dev.booky.alts.AltHelperMain
api-version: 1.18
load: STARTUP
authors: [ booky10 ]
website: https://booky.dev/

commands:
  althelper:
    permission: althelper.use
    aliases: [ alts ]
    usage: 'Usage: /<command> [all|<player>|<ip address>]'
