name: AltHelper
version: ${version}
main: tk.booky.althelper.AltHelperMain
api-version: 1.18
load: STARTUP
authors: [ booky10 ]
website: https://booky.tk/

commands:
  althelper:
    permission: althelper.use
    usage: 'Usage: /<command> [all|player|address]'
