[versions]
pluginyml = "0.6.0"
runtask = "2.3.0"
shadow = "8.1.8"

paper = "1.21.9-R0.1-SNAPSHOT"
cloudcore = "1.1.0-SNAPSHOT"

commandapi = "9.5.1"
bstats = "3.0.2"

[plugins]
pluginyml-bukkit = { id = "net.minecrell.plugin-yml.bukkit", version.ref = "pluginyml" }
runtask-paper = { id = "xyz.jpenilla.run-paper", version.ref = "runtask" }
shadow = { id = "io.github.goooler.shadow", version.ref = "shadow" }

[libraries]
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
cloudcore = { module = "dev.booky:cloudcore", version.ref = "cloudcore" }

commandapi-bukkit-core = { module = "dev.jorel:commandapi-bukkit-core", version.ref = "commandapi" }
commandapi-bukkit-plugin = { module = "dev.jorel:commandapi-bukkit-plugin", version.ref = "commandapi" }
bstats = { module = "org.bstats:bstats-bukkit", version.ref = "bstats" }
